version: "3"
services:
  mysql:
    image: mysql:5.7
    restart: always
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_DATABASE=nms
  mongo:
    image: mongo:latest
    restart: always
    expose:
      - "27017"
    ports:
      - "27017:27017"
  activemq:
    image: rmohr/activemq
    restart: always
    expose:
      - "5672"
    ports:
      - "5672:5672"
  neo4j:
    image: neo4j:4.2.1
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - "${CONTROLLER_VOL}/neo4j/plugins:/plugins"
      - "${CONTROLLER_VOL}/neo4j/data:/data"
    environment:
      - NEO4J_AUTH=neo4j/12345
      - NEO4J_dbms_logs_debug_level=DEBUG
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      - NEO4J_dbms_security_procedures_whitelist=apoc.*,algo.*
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    ports:
      - "9200:9200"
      - "9300:9300"
    command: elasticsearch
    environment:
      - discovery.type=single-node
      - discovery.seed_hosts=elasticsearch
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  logstash:
    image: docker.elastic.co/logstash/logstash:7.15.1
    ports:
      - "12201:12201/udp"
    command: -e 'input { gelf { host => "0.0.0.0" port => 12201 } }
              output { elasticsearch { hosts => ["elasticsearch"] } }'
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.1
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    links:
      - elasticsearch
      - logstash
    depends_on:
      - logstash