version: "2"
services:
  mysql:
    image: mysql:5.7
    restart: always
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_DATABASE=nms
  mongo:
    image: mongo:latest
    expose:
      - "27017"
  telemetry-microservice:
    image: nms/telemetry-microservice
    links:
      - mongo
    depends_on:
      - mongo
    expose:
      - "8082"
  topology-microservice:
    image: nms/topology-microservice
    links:
      - mysql
    depends_on:
      - mysql
    expose:
      - "8085"
  fault-microservice:
    image: nms/fault-microservice
    links:
      - mongo
    depends_on:
      - mongo
    expose:
      - "8086"
  api-gateway:
    image: nms/api-gateway
    ports:
      - "8787:8787"
    environment:
      - JAVA_OPTS="-Xms128m -Xmx256m"
    extra_hosts:
      - "dockernet:${EXTERNAL_IP}"
