version: "2"
services:
  mysql:
    image: mysql:5.7
    restart: always
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_DATABASE=nms
  mongo:
    image: mongo:latest
    expose:
      - "27017"
  account-microservice:
    image: nms/account-microservice
    links:
      - mongo
    depends_on:
      - mongo
    expose:
      - "8083"
  telemetry-microservice:
    image: nms/telemetry-microservice
    links:
      - mongo
    depends_on:
      - mongo
    expose:
      - "8082"
  notification-microservice:
    image: nms/notification-microservice
    links:
      - mongo
    depends_on:
      - mongo
    expose:
      - "8086"
  topology-microservice:
    image: nms/topology-microservice
    links:
      - mysql
      - notification-microservice
    depends_on:
      - mysql
      - notification-microservice
    expose:
      - "8085"
  configuration-microservice:
    image: nms/configuration-microservice
    links:
      - mongo
      - topology-microservice
    depends_on:
      - mongo
      - topology-microservice
    expose:
      - "8088"
  api-gateway:
    image: nms/api-gateway
    ports:
      - "8787:8787"
      - "8888:8888"
    environment:
      - JAVA_OPTS="-Xms128m -Xmx256m"
    extra_hosts:
      - "dockernet:${EXTERNAL_IP}"
