version: "3"
services:
  mysql:
    image: mysql:5.7
    restart: always
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_DATABASE=nms
    networks: 
      - nms
  mongo:
    image: mongo:latest
    restart: always
    expose:
      - "27017"
    networks: 
      - nms
  activemq:
    image: rmohr/activemq
    restart: always
    expose:
      - "5672"
    ports:
      - "5672:5672"
    networks: 
      - nms
  neo4j:
    image: neo4j:4.2.1
    restart: always
    expose:
      - "7474"
      - "7687"
    volumes:
      - "${DB_VOL}/neo4j/plugins:/plugins"
      - "${DB_VOL}/neo4j/data:/data"
    environment:
      - NEO4J_AUTH=neo4j/12345
      - NEO4J_dbms_logs_debug_level=DEBUG
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      - NEO4J_dbms_security_procedures_whitelist=apoc.*,algo.*
    networks: 
      - nms
  account-microservice:
    image: account-microservice
    links:
      - mongo
    depends_on:
      - mongo
    expose:
      - "8083"
    networks: 
      - nms
  telemetry-microservice:
    image: telemetry-microservice
    links:
      - mongo
      - activemq
    depends_on:
      - mongo
      - activemq
    expose:
      - "8082"
    networks: 
      - nms
  notification-microservice:
    image: notification-microservice
    links:
      - mongo
    depends_on:
      - mongo
    expose:
      - "8086"
    networks: 
      - nms
  topology-microservice:
    image: topology-microservice
    links:
      - mysql
      - notification-microservice
    depends_on:
      - mysql
      - notification-microservice
    expose:
      - "8085"
    networks: 
      - nms
  digitaltwin-microservice:
    image: digitaltwin-microservice
    links:
      - neo4j
    depends_on:
      - neo4j
    expose:
      - "8084"
    networks: 
      - nms
  qnet-microservice:
    image: qnet-microservice
    links:
      - mysql
      - topology-microservice
      - notification-microservice
    depends_on:
      - mysql
      - topology-microservice
      - notification-microservice
    expose:
      - "8089"
    networks: 
      - nms
  ndnet-microservice:
    image: ndnet-microservice
    links:
      - mongo
      - topology-microservice
    depends_on:
      - mongo
      - topology-microservice
    expose:
      - "8088"
    networks: 
      - nms
  api-gateway:
    image: api-gateway
    hostname: mnms.controller
    ports:
      - "8787:8787"
    environment:
      - JAVA_OPTS="-Xms128m -Xmx256m"
    extra_hosts:
      - "dockernet:${EXTERNAL_IP}"
    networks: 
      - nms
    volumes:
      - "${CERTS_VOL}:/opt/data"
networks:
  nms:
    driver: bridge